[book]
authors = ["Alen Kis"]
language = "en"
multilingual = false
src = "content"
title = "Functional Programming in Typescript"
[output.html]
git-repository-url = "https://github.com/alenkis/functional-programming-typescript-book"
additional-css = ["custom.css"]
